# Initialize array in Numpy

In [12]:
import numpy as np

In [13]:
n1 = np.array([1,2,3,4,5])

In [14]:
n1

array([1, 2, 3, 4, 5])

# Create 2d Array with all zeros using zeros method

In [15]:
n2 = np.zeros((2,3))


In [16]:
n2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
n3 = np.zeros((10,10))

In [18]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# np.Full function for 2d array with specificvalue

In [19]:
n4 = np.full((3,3),10)

In [20]:
n4


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# initialize numpy array within a range

In [21]:
n5 = np.arange(10,20)

In [22]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
n6 = np.arange(10,20,2)

In [24]:
n6

array([10, 12, 14, 16, 18])

# initialize numpy array with random numbers 

In [31]:
n7 = np.random.randint(1,100,5)

In [32]:
n7

array([62, 27, 98, 51, 81])

# know the shape of array

In [34]:
n7.shape

(5,)

# join 2 arrays

In [46]:
n8 = np.array([1,2,3,4])

In [47]:
n8

array([1, 2, 3, 4])

In [48]:
n9 = np.array([4,5,6,7])

In [49]:
n9

array([4, 5, 6, 7])

In [50]:
#vstack means vertically stack 2 arrays
np.vstack((n8,n9))

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [51]:
#hstack means horizontally stack 2 arrays
np.hstack((n8,n9))

array([1, 2, 3, 4, 4, 5, 6, 7])

In [52]:
#Column stack forjoin through columns 
np.column_stack((n8,n9))

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

# Intersection in Numpy Array

In [53]:
np.intersect1d(n8,n9)

array([4])

#  check differenc in arrays

In [54]:
np.setdiff1d(n9,n8)

array([5, 6, 7])

In [55]:
np.setdiff1d(n8,n9)

array([1, 2, 3])

#  add two arrays

In [56]:
np.sum([n8,n9])

32

In [57]:
#add by column with axis = 0
np.sum([n8,n9],axis=0)

array([ 5,  7,  9, 11])

In [58]:
#by column
np.sum([n8,n9],axis=1)

array([10, 22])

#  numpy array mathemetics


In [59]:
n10 = np.array([10,20,30])

In [60]:
n10+1

array([11, 21, 31])

In [61]:
n10-1

array([ 9, 19, 29])

In [62]:
n10*10

array([100, 200, 300])

#  Mean Median Standard deviation

In [63]:
np.mean(n10)

20.0

In [64]:
np.median(n10)

20.0

In [65]:
np.std(n10)

8.16496580927726

#  save and load numpy arrays

In [66]:
n = np.array([10,20,30,40,50])

In [67]:
np.save('array_n',n)

In [69]:
nn = np.load('array_n.npy')

In [70]:
nn

array([10, 20, 30, 40, 50])